# Cloudflare Workers configuration (migrated from Pages)
name = "hafestuswebsite"
compatibility_date = "2025-01-01"
main = "./worker/index.js"

# Custom domain routing
routes = [
  { pattern = "www.hafestus.com/*", zone_name = "hafestus.com" }
]

# Enable preview URLs for development
preview_urls = true

# Use workers.dev subdomain
workers_dev = true

# Assets configuration (was pages_build_output_dir)
[assets]
directory = "./repo"
not_found_handling = "single-page-application"
binding = "ASSETS"
