# Cloudflare Workers configuration (migrated from Pages)
name = "hafestuswebsite"
compatibility_date = "2025-01-01"
# main will be set dynamically based on environment

# Enable preview URLs for development
preview_urls = true

# Use workers.dev subdomain
workers_dev = true

# Assets configuration (was pages_build_output_dir)
[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
